{{- if .Values.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{  .Values.clusterRole.name | default (include "examplechart.fullname" .) }} 
  labels:
    {{- include "examplechart.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.clusterRole.rules | nindent 2 }}
{{- end }}
