{{- if .Values.clusterRoleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{  .Values.clusterRoleBinding.name | default (include "examplechart.fullname" .)  }}
  labels:
    {{- include "examplechart.labels" . | nindent 4 }}
roleRef:
  apiGroup: {{ .Values.clusterRoleBinding.roleRef.apiGroup }}
  kind: {{ .Values.clusterRoleBinding.roleRef.kind }}
  name: {{ .Values.clusterRoleBinding.roleRef.name }}
subjects:
  {{- toYaml .Values.clusterRoleBinding.subjects | nindent 2 }}
{{- end }}
