{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name | default (include "examplechart.fullname" .) }}
  labels:
    {{- include "examplechart.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}
{{- end }}
