{{- if .Values.roleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{  .Values.roleBinding.name | default (include "examplechart.fullname" .)  }}
  labels:
    {{- include "examplechart.labels" . | nindent 4 }}
roleRef:
  apiGroup: {{ .Values.roleBinding.roleRef.apiGroup }}
  kind: {{ .Values.roleBinding.roleRef.kind }}
  name: {{ .Values.roleBinding.roleRef.name }}
subjects:
  {{- toYaml .Values.roleBinding.subjects | nindent 2 }}
{{- end }}
