{{- if .Values.role.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{  .Values.role.name | default (include "examplechart.fullname" .)  }}
  labels:
    {{- include "examplechart.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.role.rules | nindent 2 }}
{{- end }}
