{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "examplechart.fullname" .) }}
  labels:
    {{- include "examplechart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
  {{- if .Values.secret.enabled }}
  POSTGRES_PASSWORD: {{ .Values.secret.data.POSTGRES_PASSWORD | default "dXNlcg==" }}  # Base64 encoded password
  {{- end }}
{{- end }}
